package Collections.Maps;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

public class RemovingElementsFromMap {

    public static void main(String[] args) {

        Map<String, Integer> myMap = new HashMap<>();
        myMap.put("A", 1); myMap.put("B", 2);
        myMap.put("C", 3); myMap.put("D", 4);
        myMap.put("E", 5); myMap.put("F", 6);

        //Proper way to delete objects from a collection
        Iterator<Map.Entry<String, Integer>> myIter = myMap.entrySet().iterator();
        while (myIter.hasNext()) { //The loop could be replaced with Collection.removeIf
            Map.Entry<String, Integer> myEntry2 = myIter.next();
            if(myEntry2.getKey().equals("A")){
                myIter.remove();//This will remove <A,1> from myMap
            }
        }

        //..Using the autogenerated method by Intellij in response to the above warning:
        myMap.entrySet().removeIf(myEntry2 -> myEntry2.getKey().equals("A"));//Does this also give any performance benefits?
    }

}
